import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Ghibli Success",
  authors: [{ name: "Ghibli Success" }],
  creator: "Ghibli Success",
  publisher: "Ghibli Success",
  keywords: ["Ghibli", "Success", "Kodama", "Clouds"],
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`bg-primary/20 backdrop-blur-3xl ${geist.variable}`}>
      <body>{children}</body>
    </html>
  );
}
